### ISSUE TITLE
Missing Comparisons

### ISSUE THREAD

**Issue by AI-Zhpp** [Syliz517/CLIP-ReID#1]
Thanks for releasing this code for CLIP-based Re-ID. This is a good try for improving Re-ID. However, I find some key concerns:
1. Overclaims
In fact, your work is not the first work that adopts CLIP for Re-ID. Please check the following paper in MMSports ’22, October 10, 2022,
Konrad Habel et al., CLIP-ReIdent: Contrastive Training for Player Re-Identification
Besides, I think the part of related work is not full. In fact, there are many other Transformer-based methods should be discussed. For example, HAT ([HAT: Hierarchical Aggregation Transformers for Person Re-identification]) has already used multi-level supervison ( Similarly highligted in the last sentence of your Training details). LAFomer use local-aware tranformer for re-identification.
It is better for the authors to modify these contents. 

2.Missing the key comparisions
I appreciate the authors provide the ablations. However, what is the effect of using the multi-level supervison (Note that we also employ Ltri after the 11th transformer layer of ViT-B/16 and the 3rd residual layer of ResNet-50.)？ In fact, this supervison generally shows better results than supervision with the last layer.  This may lead to unfair comparisons. 

Since the training need feeding all images. what are the training times and test speed with your devices (also not listed)?

**Comment by Syliz517** [comment]
Thanks for your suggestions, I will take them into account and revise the paper. The effect of the multi-level supervison and the training time of the first stage have been illustrated in supplementary material.

**Comment by yu9s** [comment]
不能多卡训练吗
