### ISSUE TITLE
text encoder is not fixed in first stage training

### ISSUE THREAD

**Issue by mensaochun** [Syliz517/CLIP-ReID#11]
As the paper describe, in first stage the text and image encoder is fixed, only optimize the text tokens. However, in the code, it seems the text encoder is optimized during training. Could I ask if I misunderstand?

**Comment by Syliz517** [comment]
Have a look at [solver/make_optimizer_prompt.py](https://github.com/Syliz517/CLIP-ReID/blob/master/solver/make_optimizer_prompt.py)

**Comment by Zzhc3321** [comment]
> Have a look at [solver/make_optimizer_prompt.py](https://github.com/Syliz517/CLIP-ReID/blob/master/solver/make_optimizer_prompt.py)

Encountered an issue while training stage1, 'AssertionError: No inf checks were recorded for this optimizer.' The printed output of loss is not a problem, and the problem may be that it does not cover all backpropagation model parameters. May I ask if the author has encountered this situation before.

**Comment by Syliz517** [comment]
> 
> Encountered an issue while training stage1, 'AssertionError: No inf checks were recorded for this optimizer.' The printed output of loss is not a problem, and the problem may be that it does not cover all backpropagation model parameters. May I ask if the author has encountered this situation before.

Did you change the model? Probably because the optimizer has no parameters fed into it, only the parameters in prompt_learner are fed into the optimizer in the first stage.
