### ISSUE TITLE
About training process 

### ISSUE THREAD

**Issue by YangJae96** [Syliz517/CLIP-ReID#12]
Hi. Thanks for your great work!

Can I ask about the explanation of the code execution?

If I want to reproduce the Market1501 result of your paper with CNN baseline,

do I first need to training img encoder with Strong re-ID method, using code below?
* CUDA_VISIBLE_DEVICES=0 python train.py --config_file configs/person/cnn_base.yml

And I if have both pretrained image encoder and text encoder, does the below code run stage 1 training to optimize learnable tokens 
and also stage 2 training?
* CUDA_VISIBLE_DEVICES=0 python train_clipreid.py --config_file configs/person/cnn_clipreid.yml

But where is the text encoder training? Is it automatically loaded in the code?

Also, how should I test the CNN based model after training stage2.

Thanks in advance.

**Comment by Syliz517** [comment]
Hello, you just need to run 
`CUDA_VISIBLE_DEVICES=0 python train_clipreid.py --config_file configs/person/cnn_clipreid.yml`
this code will run the first and second phases and the text encoder training is included in it.

If you want to test the CNN based model, you can refer to ViT's test:
`CUDA_VISIBLE_DEVICES=0 python test_clipreid.py --config_file configs/person/cnn_clipreid.yml TEST.WEIGHT 'your_trained_checkpoints_path/RN50_120.pth'`

**Comment by SuperbTUM** [comment]
I guess the attached explanation image is a bit misleading...
