### ISSUE TITLE
Failed to export the model to ONNX

### ISSUE THREAD

**Issue by jayong-sv** [Syliz517/CLIP-ReID#44]
I want to use my model in the ONNX format for deployment purposes.

### Description:
I encountered a runtime error while trying to export a PyTorch model to ONNX format. The error message indicates an internal assertion failure related to the `aten::eq` operation. Here are the details of the error and the code snippet used for the export.

#### Error Message:
```
RuntimeError: 0 INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":621, please report a bug to PyTorch. We don't have an op for aten::eq but it isn't a special case.  Argument types: Tensor, bool, 
Candidates:
    aten::eq.Tensor(Tensor self, Tensor other) -> Tensor
    aten::eq.Scalar(Tensor self, Scalar other) -> Tensor
    aten::eq.Scalar_out(Tensor self, Scalar other, *, Tensor(a!) out) -> Tensor(a!)
    aten::eq.Tensor_out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!)
    aten::eq.int_list(int[] a, int[] b) -> bool
    aten::eq.device(Device a, Device b) -> bool
    aten::eq.bool(bool a, bool b) -> bool
    aten::eq.enum(AnyEnumType a, AnyEnumType b) -> bool
    aten::eq.int(int a, int b) -> bool
    aten::eq.complex(complex a, complex b) -> bool
    aten::eq.float(float a, float b) -> bool
    aten::eq.int_float(int a, float b) -> bool
    aten::eq.float_int(float a, int b) -> bool
    aten::eq.float_complex(float a, complex b) -> bool
    aten::eq.complex_float(complex a, float b) -> bool
    aten::eq(Scalar a, Scalar b) -> bool
    aten::eq.str(str a, str b) -> bool
    aten::eq.float_list(float[] a, float[] b) -> bool
    aten::eq.Tensor_list(Tensor[] a, Tensor[] b) -> bool
    aten::eq.bool_list(bool[] a, bool[] b) -> bool
    aten::eq.str_list(str[] a, str[] b) -> bool
```

#### Code Snippet:
```python
# cnn_clipreid and vit_clipreid models both failed.
model.eval()

inp = [torch.randn((1, 3, 256, 128), requires_grad=False)]
model(*inp)
torch.onnx.export(
    model, tuple(inp), onnx_path,
    export_params=True,
    training=torch.onnx.TrainingMode.PRESERVE,
    do_constant_folding=False,
    opset_version=17
)
```

#### System Information:
- **OS:** ubuntu 20.04
- **PyTorch Version:** Tried with pytorch==1.8.0 (failed) and torch==2.3.1 (failed)
- **Python Version:**  3.10.9

I would greatly appreciate any insights into which part of the model might be causing the above error.

**Comment by zerobest** [comment]
Have you solved this problem yet

**Comment by jayong-sv** [comment]
@zerobest  

The issue was caused by[ comparing a boolean using equal (==)](https://github.com/Syliz517/CLIP-ReID/blob/eb1898b72c882875f478bebfc6d41644eece0a5d/model/make_model_clipreid.py#L108). I changed `if get_text == True` to `if text`, and now the conversion to ONNX works fine. However, I only verified that the conversion was successful, and I haven't checked if the inference works correctly after conversion.
