### ISSUE TITLE
Duke数据集

### ISSUE THREAD

**Issue by flycode001** [Syliz517/CLIP-ReID#5]
请问文章被接收了吗，有Duke数据集会不会被要求删除这个数据集的试验

**Comment by Syliz517** [comment]
已被接收



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月04日 14:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Syliz517/CLIP-ReID] Duke数据集 (Issue #5) |

请问文章被接收了吗，有Duke数据集会不会被要求删除这个数据集的试验
