### ISSUE TITLE
Training CLIP-ReID on a Custom Dataset: Player Re-identification Challenge

### ISSUE THREAD

**Issue by AtomScott** [Syliz517/CLIP-ReID#6]
Hello CLIP-ReID maintainers,

First off, I want to thank you all for creating and maintaining this incredible repository.

I'm writing this issue to seek guidance on a particular aspect of using CLIP-ReID: training the model on a custom dataset. The dataset I'm interested in is from the 'Player Re-identification Challenge' repository, which you can find [here](https://github.com/DeepSportradar/player-reidentification-challenge).

I've gone through the code, but I couldn't find specific instructions on how to use a custom dataset for training. I have been able to train CLIP-ReID with the Market1501 dataset with no problem.

**Comment by Syliz517** [comment]
You need to write a file for this dataset to read the data, which you can refer to [player-reidentification-challenge/reid/datasets/synergyreid.py](https://github.com/DeepSportradar/player-reidentification-challenge/blob/master/reid/datasets/synergyreid.py) and [CLIP-ReID/datasets/market1501.py](https://github.com/Syliz517/CLIP-ReID/blob/master/datasets/market1501.py), and add and modify the files in the CLIP-ReID/datasets (e.g. [CLIP-ReID/datasets/make_dataloader_clipreid.py](https://github.com/Syliz517/CLIP-ReID/blob/master/datasets/make_dataloader_clipreid.py))

**Comment by Syliz517** [comment]
You need to write a file for this dataset to read the data, which you can refer to [player-reidentification-challenge/reid/datasets/synergyreid.py](https://github.com/DeepSportradar/player-reidentification-challenge/blob/master/reid/datasets/synergyreid.py) and [CLIP-ReID/datasets/market1501.py](https://github.com/Syliz517/CLIP-ReID/blob/master/datasets/market1501.py), add and modify the files in the CLIP-ReID/datasets (e.g. [CLIP-ReID/datasets/make_dataloader_clipreid.py](https://github.com/Syliz517/CLIP-ReID/blob/master/datasets/make_dataloader_clipreid.py))

**Comment by AtomScott** [comment]
Thanks, I will try that and update this thread afterwards 👍

**Comment by AtomScott** [comment]
I was able to train both cnn, vit baselines and CLIP-ReID models by creating a dataset class `SynergyReID` and adding it to `__factory` in [CLIP-ReID/datasets/make_dataloader_clipreid.py](https://github.com/Syliz517/CLIP-ReID/blob/master/datasets/make_dataloader_clipreid.py). For reference, my code is in https://github.com/AtomScott/CLIP-ReID/tree/master. 

Is it possible to load a saved checkpoint and create a distance matrix between a given query and gallery (basically just inference)?
It would be very helpful if you can point me in the right direction in how to do this! i

**Comment by Syliz517** [comment]
You may need to modify the R1_mAP_eval in [CLIP-ReID/utils/metrics.py](https://github.com/Syliz517/CLIP-ReID/blob/master/utils/metrics.py) and other relevant codes.

**Comment by AtomScott** [comment]
Thank you for your assistance. I am happy to report that I have successfully completed the task.

**Comment by bit-scientist** [comment]
Hi, @AtomScott, could you by any chance post your training steps so that others can refer to and learn? Thanks
