### ISSUE TITLE
[Question] Unexpected Performance Drop with ViT/L14?

### ISSUE THREAD

**Issue by AtomScott** [Syliz517/CLIP-ReID#7]
I have been playing about with your CLIP ReID model and I appreciate the effectiveness of your approach. 

Recently, I conducted an experiment on Market-1501 to investigate whether we can further improve the performance of the model by using a larger model architecture. Specifically, I replaced the ViT-B16 backbone in the model with ViT/L14 (I changed the projection planes in make_clip_reid.py to make it work etc.). Intuitively, one might expect that a larger model would deliver better performance. However, the results were counterintuitive.

Here are the results obtained with the original ViT-B/16:
```
mAP: 89.8%
CMC curve, Rank-1  :95.3%
CMC curve, Rank-5  :98.6%
CMC curve, Rank-10 :99.2%
```

And here are the results obtained with the ViT-L/14:
```
mAP: 79.1%
CMC curve, Rank-1  :90.7%
CMC curve, Rank-5  :96.7%
CMC curve, Rank-10 :98.1%
```
It appears that the performance with the ViT/L14 architecture is significantly lower than with the ViT-B16. I double-checked the modifications and ensured that the experiment settings were identical, save for the architecture swap.

For reference, I'm attaching the training logs of both models:

[train_log-market1501-V14.txt](https://github.com/Syliz517/CLIP-ReID/files/12009954/train_log-market1501-V14.txt)
[train_log-market1501-B16.txt](https://github.com/Syliz517/CLIP-ReID/files/12009955/train_log-market1501-B16.txt)

I would greatly appreciate your insights into why the ViT/L14 architecture might underperform compared to ViT-B16 in this context. I am new to using ViT models in ReID so any guidance on how the model could potentially be fine-tuned for the larger architecture would also be appreciated!

**Comment by Syliz517** [comment]
Hi, our current code uses ViT-B/16 which has 12 layers of transformers, so in [model/clip/model.py](https://github.com/Syliz517/CLIP-ReID/blob/master/model/clip/model.py), we extract the features of the 12th and 11th layer. If you want to use ViT-L/14, you need to modify the extracted feature layers to the last two layers. Our result using ViT-L/14 is as follows:
```
mAP: 92.3%
CMC curve, Rank-1  :95.8%
CMC curve, Rank-5  :98.8%
CMC curve, Rank-10 :99.4%
```
We will update the code later.

**Comment by AtomScott** [comment]
Wow! Nice results! Looking forward to the code updates.
