### ISSUE TITLE
Center loss being ignored

### ISSUE THREAD

**Issue by awarebayes** [Syliz517/CLIP-ReID#9]
I have noticed that you do not use center loss, despite setting up optimizer for it and adding centroid scaling.
https://github.com/Syliz517/CLIP-ReID/blob/5b92124ec041c1c7a9fa1ac7ee9b86a5d45ac4ad/processor/processor_clipreid_stage2.py#L13
It's just not being called with loss function.
Can I ask why? I have implemented it myself, but I am yet to see how it works

**Comment by Syliz517** [comment]
This part of the code follows Transreid, I didn't change it.
